import { useState } from 'react';
import toast from 'react-hot-toast';
import PromptForm from '../components/PromptForm';
import AdPreview from '../components/AdPreview';
import { generateAd } from '../api/adsApi';

function GeneratePage() {
  const [loading, setLoading] = useState(false);
  const [campaign, setCampaign] = useState(null);
  const [generationCount, setGenerationCount] = useState(0);

  const handleGenerate = async (formData) => {
    setLoading(true);
    try {
      const data = await generateAd(formData);
      setCampaign(data);
      setGenerationCount((count) => count + 1);
      toast.success('Ad generated successfully');
    } catch (error) {
      const message = error?.response?.data?.message || 'Failed to generate ad';
      toast.error(message);
    } finally {
      setLoading(false);
    }
  };

  return (
    <main className="page">
      <section className="hero">
        <span className="hero-tag">AI-Powered Ad Studio</span>
        <h1>
          Turn a product thought into a high-converting <em>social ad</em>
        </h1>
        <p>
          Prompt once, get a platform-ready visual, caption, and hashtags generated by AI in under a minute.
        </p>
      </section>

      <section className="generate-layout">
        <PromptForm loading={loading} onGenerate={handleGenerate} />
        <AdPreview loading={loading} campaign={campaign} generationCount={generationCount} />
      </section>
    </main>
  );
}

export default GeneratePage;
